// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNNGE34OZgH1s80ZrQCZOvLsu2rUs-fP8',
    appId: '1:213976987974:android:29183ab830844ab6428d47',
    messagingSenderId: '213976987974',
    projectId: 'budgetlab-6e9dd',
    storageBucket: 'budgetlab-6e9dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr5qy_wNY4pNVKYSXfQnyxQu2sAvPX2C4',
    appId: '1:213976987974:ios:db2b99b9f2fef20d428d47',
    messagingSenderId: '213976987974',
    projectId: 'budgetlab-6e9dd',
    storageBucket: 'budgetlab-6e9dd.appspot.com',
    iosClientId: '213976987974-k10i81ievdmblkugndvo9977oca6mjha.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr5qy_wNY4pNVKYSXfQnyxQu2sAvPX2C4',
    appId: '1:213976987974:ios:db2b99b9f2fef20d428d47',
    messagingSenderId: '213976987974',
    projectId: 'budgetlab-6e9dd',
    storageBucket: 'budgetlab-6e9dd.appspot.com',
    iosClientId: '213976987974-k10i81ievdmblkugndvo9977oca6mjha.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetlab',
  );
}
