// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'BudgetModule/Budgets/budgetsExpences_entity.dart';
import 'BudgetModule/Budgets/budgets_entity.dart';
import 'BudgetModule/IncomeExpense/incomeExpense_entity.dart';
import 'BudgetModule/LoanLend/loanLend_entity.dart';
import 'SettingsModule/User/metadata_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6802996608281474169),
      name: 'Budgets',
      lastPropertyId: const IdUid(7, 8391892081381294465),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7892491605148104479),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6886238290113684430),
            name: 'income',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 505438653172455670),
            name: 'amount',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1607658015042254482),
            name: 'repeatingAmount',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 1948691181366621843),
            name: 'note',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2680095188841296466),
            name: 'repeats',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 8391892081381294465),
            name: 'icon',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 5763167720482628840),
      name: 'BudgetsExpences',
      lastPropertyId: const IdUid(5, 412387457098610842),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7221082646700696975),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1257878316410507015),
            name: 'amount',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1447215159750224541),
            name: 'dateTime',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2301918330405112066),
            name: 'note',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 412387457098610842),
            name: 'image',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 6320807187947101828),
      name: 'IncomeExpense',
      lastPropertyId: const IdUid(5, 6849478080056154371),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1669841428554488936),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8255559117702534497),
            name: 'income',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4500954133982054754),
            name: 'dateTime',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 6205658066235227687),
            name: 'amount',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 6849478080056154371),
            name: 'note',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 7538554346552189482),
      name: 'LoanLend',
      lastPropertyId: const IdUid(7, 6280790061080855288),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4292127804344261869),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6833607976943648271),
            name: 'loan',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3876860853412484563),
            name: 'dateTime',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2895427546366819012),
            name: 'amount',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7628047489849571575),
            name: 'note',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 5306888962846670714),
            name: 'phone',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 6280790061080855288),
            name: 'returnStatus',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(5, 6126941312004195708),
      name: 'Metadata',
      lastPropertyId: const IdUid(10, 1806408444337177575),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4186639016069329190),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2689884158161646771),
            name: 'currentBalance',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4248981470283217906),
            name: 'yourWorth',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8894507846808041198),
            name: 'userName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 1109312081956126273),
            name: 'currency',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 1624813757010844870),
            name: 'country',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1212614887772630539),
            name: 'countryCode',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 2523403120950611236),
            name: 'password',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 4440690523450898142),
            name: 'hideOn',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 1806408444337177575),
            name: 'readMessage',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(5, 6126941312004195708),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Budgets: EntityDefinition<Budgets>(
        model: _entities[0],
        toOneRelations: (Budgets object) => [],
        toManyRelations: (Budgets object) => {},
        getId: (Budgets object) => object.id,
        setId: (Budgets object, int id) {
          object.id = id;
        },
        objectToFB: (Budgets object, fb.Builder fbb) {
          final noteOffset = fbb.writeString(object.note);
          final repeatsOffset = fbb.writeString(object.repeats);
          final iconOffset = fbb.writeString(object.icon);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.income);
          fbb.addInt64(2, object.amount);
          fbb.addInt64(3, object.repeatingAmount);
          fbb.addOffset(4, noteOffset);
          fbb.addOffset(5, repeatsOffset);
          fbb.addOffset(6, iconOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Budgets(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              income:
                  const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false),
              amount:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              repeatingAmount:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              note: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              repeats: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              icon: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, ''));

          return object;
        }),
    BudgetsExpences: EntityDefinition<BudgetsExpences>(
        model: _entities[1],
        toOneRelations: (BudgetsExpences object) => [],
        toManyRelations: (BudgetsExpences object) => {},
        getId: (BudgetsExpences object) => object.id,
        setId: (BudgetsExpences object, int id) {
          object.id = id;
        },
        objectToFB: (BudgetsExpences object, fb.Builder fbb) {
          final noteOffset = fbb.writeString(object.note);
          final imageOffset = fbb.writeString(object.image);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.amount);
          fbb.addInt64(2, object.dateTime.millisecondsSinceEpoch);
          fbb.addOffset(3, noteOffset);
          fbb.addOffset(4, imageOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = BudgetsExpences(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              amount:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              dateTime: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)),
              note: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              image: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''));

          return object;
        }),
    IncomeExpense: EntityDefinition<IncomeExpense>(
        model: _entities[2],
        toOneRelations: (IncomeExpense object) => [],
        toManyRelations: (IncomeExpense object) => {},
        getId: (IncomeExpense object) => object.id,
        setId: (IncomeExpense object, int id) {
          object.id = id;
        },
        objectToFB: (IncomeExpense object, fb.Builder fbb) {
          final noteOffset = fbb.writeString(object.note);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.income);
          fbb.addInt64(2, object.dateTime.millisecondsSinceEpoch);
          fbb.addInt64(3, object.amount);
          fbb.addOffset(4, noteOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = IncomeExpense(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              income:
                  const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false),
              dateTime: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)),
              amount:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              note: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''));

          return object;
        }),
    LoanLend: EntityDefinition<LoanLend>(
        model: _entities[3],
        toOneRelations: (LoanLend object) => [],
        toManyRelations: (LoanLend object) => {},
        getId: (LoanLend object) => object.id,
        setId: (LoanLend object, int id) {
          object.id = id;
        },
        objectToFB: (LoanLend object, fb.Builder fbb) {
          final noteOffset = fbb.writeString(object.note);
          final phoneOffset = fbb.writeString(object.phone);
          final returnStatusOffset = fbb.writeString(object.returnStatus);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.loan);
          fbb.addInt64(2, object.dateTime.millisecondsSinceEpoch);
          fbb.addInt64(3, object.amount);
          fbb.addOffset(4, noteOffset);
          fbb.addOffset(5, phoneOffset);
          fbb.addOffset(6, returnStatusOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = LoanLend(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              loan:
                  const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false),
              dateTime: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)),
              amount:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              note: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              phone: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              returnStatus: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, ''));

          return object;
        }),
    Metadata: EntityDefinition<Metadata>(
        model: _entities[4],
        toOneRelations: (Metadata object) => [],
        toManyRelations: (Metadata object) => {},
        getId: (Metadata object) => object.id,
        setId: (Metadata object, int id) {
          object.id = id;
        },
        objectToFB: (Metadata object, fb.Builder fbb) {
          final userNameOffset = fbb.writeString(object.userName);
          final currencyOffset = fbb.writeString(object.currency);
          final countryOffset = fbb.writeString(object.country);
          final passwordOffset = fbb.writeString(object.password);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.currentBalance);
          fbb.addInt64(2, object.yourWorth);
          fbb.addOffset(3, userNameOffset);
          fbb.addOffset(4, currencyOffset);
          fbb.addOffset(5, countryOffset);
          fbb.addInt64(6, object.countryCode);
          fbb.addOffset(7, passwordOffset);
          fbb.addBool(8, object.hideOn);
          fbb.addBool(9, object.readMessage);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Metadata(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              currentBalance:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              yourWorth:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              userName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              currency: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              country: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              countryCode:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
              password: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, ''),
              hideOn: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 20, false),
              readMessage: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 22, false));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Budgets] entity fields to define ObjectBox queries.
class Budgets_ {
  /// see [Budgets.id]
  static final id = QueryIntegerProperty<Budgets>(_entities[0].properties[0]);

  /// see [Budgets.income]
  static final income =
      QueryBooleanProperty<Budgets>(_entities[0].properties[1]);

  /// see [Budgets.amount]
  static final amount =
      QueryIntegerProperty<Budgets>(_entities[0].properties[2]);

  /// see [Budgets.repeatingAmount]
  static final repeatingAmount =
      QueryIntegerProperty<Budgets>(_entities[0].properties[3]);

  /// see [Budgets.note]
  static final note = QueryStringProperty<Budgets>(_entities[0].properties[4]);

  /// see [Budgets.repeats]
  static final repeats =
      QueryStringProperty<Budgets>(_entities[0].properties[5]);

  /// see [Budgets.icon]
  static final icon = QueryStringProperty<Budgets>(_entities[0].properties[6]);
}

/// [BudgetsExpences] entity fields to define ObjectBox queries.
class BudgetsExpences_ {
  /// see [BudgetsExpences.id]
  static final id =
      QueryIntegerProperty<BudgetsExpences>(_entities[1].properties[0]);

  /// see [BudgetsExpences.amount]
  static final amount =
      QueryIntegerProperty<BudgetsExpences>(_entities[1].properties[1]);

  /// see [BudgetsExpences.dateTime]
  static final dateTime =
      QueryIntegerProperty<BudgetsExpences>(_entities[1].properties[2]);

  /// see [BudgetsExpences.note]
  static final note =
      QueryStringProperty<BudgetsExpences>(_entities[1].properties[3]);

  /// see [BudgetsExpences.image]
  static final image =
      QueryStringProperty<BudgetsExpences>(_entities[1].properties[4]);
}

/// [IncomeExpense] entity fields to define ObjectBox queries.
class IncomeExpense_ {
  /// see [IncomeExpense.id]
  static final id =
      QueryIntegerProperty<IncomeExpense>(_entities[2].properties[0]);

  /// see [IncomeExpense.income]
  static final income =
      QueryBooleanProperty<IncomeExpense>(_entities[2].properties[1]);

  /// see [IncomeExpense.dateTime]
  static final dateTime =
      QueryIntegerProperty<IncomeExpense>(_entities[2].properties[2]);

  /// see [IncomeExpense.amount]
  static final amount =
      QueryIntegerProperty<IncomeExpense>(_entities[2].properties[3]);

  /// see [IncomeExpense.note]
  static final note =
      QueryStringProperty<IncomeExpense>(_entities[2].properties[4]);
}

/// [LoanLend] entity fields to define ObjectBox queries.
class LoanLend_ {
  /// see [LoanLend.id]
  static final id = QueryIntegerProperty<LoanLend>(_entities[3].properties[0]);

  /// see [LoanLend.loan]
  static final loan =
      QueryBooleanProperty<LoanLend>(_entities[3].properties[1]);

  /// see [LoanLend.dateTime]
  static final dateTime =
      QueryIntegerProperty<LoanLend>(_entities[3].properties[2]);

  /// see [LoanLend.amount]
  static final amount =
      QueryIntegerProperty<LoanLend>(_entities[3].properties[3]);

  /// see [LoanLend.note]
  static final note = QueryStringProperty<LoanLend>(_entities[3].properties[4]);

  /// see [LoanLend.phone]
  static final phone =
      QueryStringProperty<LoanLend>(_entities[3].properties[5]);

  /// see [LoanLend.returnStatus]
  static final returnStatus =
      QueryStringProperty<LoanLend>(_entities[3].properties[6]);
}

/// [Metadata] entity fields to define ObjectBox queries.
class Metadata_ {
  /// see [Metadata.id]
  static final id = QueryIntegerProperty<Metadata>(_entities[4].properties[0]);

  /// see [Metadata.currentBalance]
  static final currentBalance =
      QueryIntegerProperty<Metadata>(_entities[4].properties[1]);

  /// see [Metadata.yourWorth]
  static final yourWorth =
      QueryIntegerProperty<Metadata>(_entities[4].properties[2]);

  /// see [Metadata.userName]
  static final userName =
      QueryStringProperty<Metadata>(_entities[4].properties[3]);

  /// see [Metadata.currency]
  static final currency =
      QueryStringProperty<Metadata>(_entities[4].properties[4]);

  /// see [Metadata.country]
  static final country =
      QueryStringProperty<Metadata>(_entities[4].properties[5]);

  /// see [Metadata.countryCode]
  static final countryCode =
      QueryIntegerProperty<Metadata>(_entities[4].properties[6]);

  /// see [Metadata.password]
  static final password =
      QueryStringProperty<Metadata>(_entities[4].properties[7]);

  /// see [Metadata.hideOn]
  static final hideOn =
      QueryBooleanProperty<Metadata>(_entities[4].properties[8]);

  /// see [Metadata.readMessage]
  static final readMessage =
      QueryBooleanProperty<Metadata>(_entities[4].properties[9]);
}
